[package]
name = "librust"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
thiserror = "2.0.14"
bitflags = "2.9.2"
os-thread-local = "0.1.3"
once_cell = "1.21.3"
cfg-if = "1.0.1"
libc = "1.0.0-alpha.1"
