use thiserror::Error;
use crate::enum_from_display;

enum_from_display!(
    #[derive(Error, Debug, Eq, PartialEq)]
    #[repr(i64)]
    pub enum Error {
        Unknown = 0 => "Unknown error",
        PermissionDenied = 1 => "Permission denied",
        NotFound = 2 => "No such file or directory",
        NoSuchProcess = 3 => "No such process",
        Interrupted = 4 => "Interrupted",
        IoError = 5 => "I/O error_types",
        NoSuchDeviceOrAddress = 6 => "No such device or address",
        ArgumentListTooLong = 7 => "Argument list too long",
        ExecFormatError = 8 => "Exec format error",
        BadFileDescriptor = 9 => "Bad file descriptor",
        NoChildProcesses = 10 => "No child processes",
        ResourceDeadlockWouldOccur = 11 => "Resource deadlock would occur",
        OutOfMemory = 12 => "Out of memory",
        AccessDenied = 13 => "Access denied",
        BadAddress = 14 => "Bad address",
        BlockDeviceRequired = 15 => "Block device required",
        DeviceBusy = 16 => "Device or resources busy",
        AlreadyExists = 17 => "File or directory already exists",
        CrossDeviceLink = 18 => "Cross-device link",
        NoSuchDevice = 19 => "No such device",
        NotDirectory = 20 => "Not a directory",
        IsDirectory = 21 => "Is a directory",
        InvalidArgument = 22 => "Invalid argument",
        FileTableOverflow = 23 => "File table overflow",
        TooManyOpenFiles = 24 => "Too many open files",
        NotTTY = 25 => "Not a TTY",
        TextFileBusy = 26 => "Text file busy",
        FileTooLarge = 27 => "File too large",
        NoSpaceLeftOnDevice = 28 => "No space left on device",
        IllegalSeek = 29 => "Illegal seek",
        ReadOnlyFilesystem = 30 => "Read-only file system",
        TooManyLinks = 31 => "Too many links",
        BrokenPipe = 32 => "Broken pipe",
        MathArgumentOutOfDomain = 33 => "Math argument out of domain",
        ResultTooLarge = 34 => "Result too large",
        ResourceUnavailableTryAgain = 35 => "Resource unavailable, try again",
        OperationInProgress = 36 => "Operation in-progress",
        OperationAlreadyInProgress = 37 => "Operation already in-progress",
        SocketNotSupported = 38 => "Socket is not supported",
        DestinationAddressRequired = 39 => "Destination address required",
        MessageTooLong = 40 => "Message too long",
        ProtocolWrongTypeForSocket = 41 => "Protocol wrong socket type",
        ProtocolNotAvailable = 42 => "Protocol is not available",
        ProtocolNotSupported = 43 => "Protocol is not supported",
        SocketTypeNotSupported = 44 => "Socket type is not supported",
        OperationNotSupported = 45 => "Operation is not supported",
        ProtocolFamilyNotSupported = 46 => "Protocol family is not supported",
        AddressFamilyNotSupported = 47 => "Address family is not supported by protocol",
        AddressInUse = 48 => "Address in use",
        AddressNotAvailable = 49 => "Address is not available",
        NetworkDown = 50 => "Network down",
        NetworkUnreachable = 51 => "Network unreachable",
        NetworkReset = 52 => "Network reset",
        ConnectionAborted = 53 => "Connection aborted",
        ConnectionReset = 54 => "Connection reset",
        NoBufferSpaceAvailable = 55 => "No buffer space available",
        SocketIsConnected = 56 => "Transport endpoint is already connected",
        SocketNotConnected = 57 => "Transport endpoint is not connected",
        Shutdown = 58 => "Cannot send after transport endpoint shutdown",
        TooManyReferences = 59 => "Too many references: cannot splice",
        TimedOut = 60 => "Connection timed out",
        ConnectionRefused = 61 => "Connection refused",
        TooManySymbolicLinks = 62 => "Too many symbolic links: cannot link",
        FileNameTooLong = 63 => "File name is too long",
        HostDown = 64 => "Host is down",
        HostUnreachable = 65 => "No route to host",
        DirectoryNotEmpty = 66 => "Directory is not empty",
        ProcessLimitReached = 67 => "Process limit reached",
        TooManyUsers = 68 => "Too many users",
        DiskQuotaExceeded = 69 => "Disk quota exceeded",
        StaleFileHandle = 70 => "Stale NFS file handle",
        RemoteResourceNotAvailable = 71 => "Too many levels of remote in path",
        BadRPC = 72 => "RPC struct is bad",
        RPCMismatch = 73 => "RPC version mismatch",
        ProgramUnavailable = 74 => "Program unavailable",
        ProgramMismatch = 75 => "Program version mismatch",
        ProcedureUnavailable = 76 => "Procedure unavailable for program",
        NoLocksAvailable = 77 => "No record locks available",
        FunctionNotImplemented = 78 => "Function is not implemented",
        InappropriateFileType = 79 => "Inappropriate file type or format",
        AuthenticationError = 80 => "Authentication error",
        NeedAuthentication = 81 => "Need authentication",
        PowerOff = 82 => "Device power off",
        DeviceError = 83 => "Device error",
        ValueOverflow = 84 => "",
        BadExecutable = 85 => "Bad executable",
        BadArchitecture = 86 => "Bad architecture",
        SharedLibraryVersionMismatch = 87 => "Shared library version mismatch",
        BadMachO = 88 => "Malformed Mach-O",
        OperationCanceled = 89 => "Operation canceled",
        IdentifierRemoved = 90 => "Identifier removed",
        NoMessageAvailable = 91 => "No message available",
        IllegalByteSequence = 92 => "Illegal byte sequence",
        AttributeNotFound = 93 => "Attribute not found",
        BadMessage = 94 => "Bad message",
        MultihopAttempted = 95 => "Multihop attempted",
        NoDataAvailable = 96 => "No data available",
        LinkHasBeenSevered = 97 => "Link has been severed",
        NoStreamResources = 98 => "No stream resources",
        NotStructuredStream = 99 => "Not a structured stream",
        ProtocolError = 100 => "Protocol error",
        TimerExpired = 101 => "Timer expired",
        OperationNotSupportedOnSocket = 102 => "Operation is not supported on socket",
        NoPolicy = 103 => "No policy",
        NotRecoverable = 104 => "Not recoverable",
        OwnerDead = 105 => "Owner dead",
        QueueFull = 106 => "Queue full",
    }
);
