use crate::enum_from_display;
use thiserror::Error;

enum_from_display!(
    #[derive(Error, Debug, Eq, PartialEq)]
    #[repr(i64)]
    pub enum Error {
        PermissionDenied = 1 => "Permission denied",
        NotFound = 2 => "No such file or directory",
        NoSuchProcess = 3 => "No such process",
        InterruptedSystemCall = 4 => "Interrupted system call",
        InputOutputError = 5 => "Input/output error",
        NoSuchDeviceOrAddress = 6 => "No such device or address",
        ArgumentListTooLong = 7 => "Argument list too long",
        ExecFormatError = 8 => "Exec format error",
        BadFileDescriptor = 9 => "Bad file descriptor",
        NoChildProcesses = 10 => "No child processes",
        ResourceTemporarilyUnavailable = 11 => "Resource temporarily unavailable",
        CannotAllocateMemory = 12 => "Cannot allocate memory",
        AccessDenied = 13 => "Access denied",
        BadAddress = 14 => "Bad address",
        BlockDeviceRequired = 15 => "Block device required",
        DeviceOrResourceBusy = 16 => "Device or resource busy",
        FileExists = 17 => "File exists",
        InvalidCrossDeviceLink = 18 => "Invalid cross-device link",
        NoSuchDevice = 19 => "No such device",
        NotADirectory = 20 => "Not a directory",
        IsADirectory = 21 => "Is a directory",
        InvalidArgument = 22 => "Invalid argument",
        TooManyOpenFilesInSystem = 23 => "Too many open files in system",
        TooManyOpenFiles = 24 => "Too many open files",
        InappropriateIoctlForDevice = 25 => "Inappropriate ioctl for device",
        TextFileBusy = 26 => "Text file busy",
        FileTooLarge = 27 => "File too large",
        NoSpaceLeftOnDevice = 28 => "No space left on device",
        IllegalSeek = 29 => "Illegal seek",
        ReadOnlyFileSystem = 30 => "Read-only file system",
        TooManyLinks = 31 => "Too many links",
        BrokenPipe = 32 => "Broken pipe",
        NumericalArgumentOutOfDomain = 33 => "Numerical argument out of domain",
        NumericalResultOutOfRange = 34 => "Numerical result out of range",
        ResourceDeadlockAvoided = 35 => "Resource deadlock avoided",
        FileNameTooLong = 36 => "File name too long",
        NoLocksAvailable = 37 => "No locks available",
        FunctionNotImplemented = 38 => "Function not implemented",
        DirectoryNotEmpty = 39 => "Directory not empty",
        TooManyLevelsOfSymbolicLinks = 40 => "Too many levels of symbolic links",
        NoMessageOfDesiredType = 42 => "No message of desired type",
        IdentifierRemoved = 43 => "Identifier removed",
        ChannelNumberOutOfRange = 44 => "Channel number out of range",
        Level2NotSynchronized = 45 => "Level 2 not synchronized",
        Level3Halted = 46 => "Level 3 halted",
        Level3Reset = 47 => "Level 3 reset",
        LinkNumberOutOfRange = 48 => "Link number out of range",
        ProtocolDriverNotAttached = 49 => "Protocol driver not attached",
        NoCSIStructureAvailable = 50 => "No CSI structure available",
        Level2Halted = 51 => "Level 2 halted",
        InvalidExchange = 52 => "Invalid exchange",
        InvalidRequestDescriptor = 53 => "Invalid request descriptor",
        ExchangeFull = 54 => "Exchange full",
        NoAnode = 55 => "No anode",
        InvalidRequestCode = 56 => "Invalid request code",
        InvalidSlot = 57 => "Invalid slot",
        BadFontFileFormat = 59 => "Bad font file format",
        DeviceNotAStream = 60 => "Device not a stream",
        NoDataAvailable = 61 => "No data available",
        TimerExpired = 62 => "Timer expired",
        OutOfStreamsResources = 63 => "Out of streams resources",
        MachineIsNotOnNetwork = 64 => "Machine is not on network",
        PackageNotInstalled = 65 => "Package not installed",
        ObjectIsRemote = 66 => "Object is remote",
        LinkHasBeenSevered = 67 => "Link has been severed",
        AdvertiseError = 68 => "Advertise error",
        SrmountError = 69 => "Srmount error",
        CommunicationErrorOnSend = 70 => "Communication error on send",
        ProtocolError = 71 => "Protocol error",
        MultihopAttempted = 72 => "Multihop attempted",
        RFSSpecificError = 73 => "RFS specific error",
        BadMessage = 74 => "Bad message",
        ValueTooLargeForDefinedDataType = 75 => "Value too large for defined data type",
        NameNotUniqueOnNetwork = 76 => "Name not unique on network",
        FileDescriptorInBadState = 77 => "File descriptor in bad state",
        RemoteAddressChanged = 78 => "Remote address changed",
        CannotAccessNeededSharedLibrary = 79 => "Cannot access a needed shared library",
        AccessingCorruptedSharedLibrary = 80 => "Accessing a corrupted shared library",
        LibSectionInAOutCorrupted = 81 => "Lib section in a.out corrupted",
        AttemptingToLinkInTooManySharedLibraries = 82 => "Attempting to link in too many shared libraries",
        CannotExecSharedLibraryDirectly = 83 => "Cannot exec a shared library directly",
        IllegalByteSequence = 84 => "Illegal byte sequence",
        RestartInterruptedSystemCall = 85 => "Restart interrupted system call",
        StreamsPipeError = 86 => "Streams pipe error",
        TooManyUsers = 87 => "Too many users",
        NotASocket = 88 => "Not a socket",
        DestinationAddressRequired = 89 => "Destination address required",
        MessageTooLong = 90 => "Message too long",
        ProtocolWrongTypeForSocket = 91 => "Protocol wrong type for socket",
        ProtocolNotAvailable = 92 => "Protocol not available",
        ProtocolNotSupported = 93 => "Protocol not supported",
        SocketTypeNotSupported = 94 => "Socket type not supported",
        OperationNotSupported = 95 => "Operation not supported",
        ProtocolFamilyNotSupported = 96 => "Protocol family not supported",
        AddressFamilyNotSupportedByProtocol = 97 => "Address family not supported by protocol",
        AddressAlreadyInUse = 98 => "Address already in use",
        CannotAssignRequestedAddress = 99 => "Cannot assign requested address",
        NetworkIsDown = 100 => "Network is down",
        NetworkIsUnreachable = 101 => "Network is unreachable",
        NetworkDroppedConnectionOnReset = 102 => "Network dropped connection on reset",
        SoftwareCausedConnectionAbort = 103 => "Software caused connection abort",
        ConnectionResetByPeer = 104 => "Connection reset by peer",
        NoBufferSpaceAvailable = 105 => "No buffer space available",
        TransportEndpointAlreadyConnected = 106 => "Transport endpoint already connected",
        TransportEndpointNotConnected = 107 => "Transport endpoint not connected",
        CannotSendAfterTransportEndpointShutdown = 108 => "Cannot send after transport endpoint shutdown",
        TooManyReferencesCannotSplice = 109 => "Too many references: cannot splice",
        OperationTimedOut = 110 => "Operation timed out",
        ConnectionRefused = 111 => "Connection refused",
        HostIsDown = 112 => "Host is down",
        NoRouteToHost = 113 => "No route to host",
        OperationAlreadyInProgress = 114 => "Operation already in progress",
        OperationNowInProgress = 115 => "Operation now in progress",
        StaleFileHandle = 116 => "Stale file handle",
        StructureNeedsCleaning = 117 => "Structure needs cleaning",
        NotAXENIXNamedTypeFile = 118 => "Not a XENIX named type file",
        NoXENIXSemaphoresAvailable = 119 => "No XENIX semaphores available",
        IsANamedTypeFile = 120 => "Is a named type file",
        RemoteIOError = 121 => "Remote I/O error",
        DiskQuotaExceeded = 122 => "Disk quota exceeded",
        NoMediumFound = 123 => "No medium found",
        WrongMediumType = 124 => "Wrong medium type",
        OperationCanceled = 125 => "Operation canceled",
        RequiredKeyNotAvailable = 126 => "Required key not available",
        KeyExpired = 127 => "Key expired",
        KeyRevoked = 128 => "Key revoked",
        KeyRejected = 129 => "Key rejected",
        OwnerDied = 130 => "Owner died",
        StateNotRecoverable = 131 => "State not recoverable",
        RFKillOperationNotPossible = 132 => "Operation not possible due to RF-kill",
        MemoryPageHasHardwareError = 133 => "Memory page has hardware error",
    }
);
