use crate::enum_from_display;
use thiserror::Error;

enum_from_display!(
    #[derive(Error, Debug, Eq, PartialEq)]
    #[repr(i64)]
    pub enum Error {
        Unknown = 0 => "unknown error",
        PermissionDenied = 1 => "Permission denied",
        NotFound = 2 => "No such file or directory",
        NoSuchProcess = 3 => "No such process",
        Interrupted = 4 => "Interrupted",
        IoError = 5 => "I/O error",
        NoSuchDeviceOrAddress = 6 => "No such device or address",
        ArgumentListTooLong = 7 => "Argument list too long",
        ExecFormatError = 8 => "Exec format error",
        BadFileDescriptor = 9 => "Bad file descriptor",
        NoChildProcesses = 10 => "No child processes",
        ResourceUnavailableTryAgain = 11 => "Resource unavailable, try again",
        OutOfMemory = 12 => "Out of memory",
        AccessDenied = 13 => "Access denied",
        BadAdress = 14 => "Bad address",
        BlockDeviceRequired = 15 => "Block device required",
        DeviceBusy = 16 => "Device busy",
        AlreadyExists = 17 => "Already exists",
        CrossDeviceLink = 18 => "Cross-device link",
        NoSuchDevice = 19 => "No such device",
        NotDirectory = 20 => "Not a directory",
        IsDirectory = 21 => "Is a directory",
        InvalidArgument = 22 => "Invalid argument",
        FileTableOverflow = 23 => "File table overflow",
        TooManyOpemFiles = 24 => "Too many open files",
        NotTTY = 25 => "Not a TTY",
        TextFileBusy = 26 => "Text file busy",
        FileTooLarge = 27 => "File too large",
        NoSpaceLeftOnDevice = 28 => "No space left on device",
        IllegalSeek = 29 => "Illegal seek",
        ReadOnlyFilesystem = 30 => "Read-only file system",
        TooManyLinks = 31 => "Too many links",
        BrokenPipe = 32 => "Broken pipe",
        MathArgumentOutOfDomain = 33 => "Math argument out of domain",
        ResultTooLarge = 34 => "Result too large",
        ResourceDeadlockAvoided = 35 => "Resource deadlock avoided",
        FileNameTooLong = 36 => "File name is too long",
        NoLockAvailable = 37 => "No lock available",
        FunctionNotImplemented = 38 => "Function is not implemented",
        DirectoryNotEmpty = 39 => "Directory is not empty",
        TooManySymbolicLinks = 40 => "Too many symbolic links",
        NoMessageAvailable = 42 => "No message available",
        IdentifierRemoved = 43 => "Identifier removed",
        ChannelNumberOutOfRange = 44 => "Channel number is out of range",
        Level2NotSycnchronised = 45 => "Level 2 is not synchronised",
        Level3Halted = 46 => "Level 3 halted",
        Level3Reset = 47 => "Level 3 reset",
        LinkNumberOutOfRange = 48 => "Link number is out of range",
        ProtocolDriverNotAttached = 49 => "Protocol driver not attached",
        NoCsiStructureAvailable = 50 => "No CSI structure available",
        Level2Halted = 51 => "Level 2 halted",
        InvalidExchange = 52 => "Invalid exchange",
        InvalidRequestDescriptor = 53 => "Invalid request descriptor",
        ExchangeFull = 54 => "Exchange full",
        NoAnode = 55 => "No anode",
        InvalidRequestCode = 56 => "Invalid request code",
        InvalidSlot = 57 => "Invalid slot",
        BadFontFileFormat = 59 => "Bad font file format",
        DeviceNotAStream = 60 => "Device not a stream",
        NoDataAvailable = 61 => "No data available",
        TimerExpired = 62 => "Timer expired",
        OutOfStreamsResources = 63 => "Out of streams resources",
        MachineNotOnNetwork = 64 => "Machine is not on the network",
        PackageNotInstalled = 65 => "Package not installed",
        ObjectIsRemote = 66 => "Object is remote",
        LinkSevered = 67 => "Link has been severed",
        AdvertiseError = 68 => "Advertise error",
        SrmountError = 69 => "Srmount error",
        CommunicationError = 70 => "Communication error on send",
        ProtocolError = 71 => "Protocol error",
        MultihopAttempted = 72 => "Multihop attempted",
        RfsSpecificError = 73 => "RFS specific error",
        BadMessage = 74 => "Bad message",
        ValueTooLarge = 75 => "Value too large for defined data type",
        NameNotUnique = 76 => "Name not unique on network",
        FileDescriptorBadState = 77 => "File descriptor in bad state",
        RemoteAddressChanged = 78 => "Remote address changed",
        CannotAccessSharedLibrary = 79 => "Cannot access a needed shared library",
        CorruptedSharedLibrary = 80 => "Accessing a corrupted shared library",
        LibSectionCorrupted = 81 => ".lib section in a.out corrupted",
        TooManySharedLibraries = 82 => "Attempting to link in too many shared libraries",
        CannotExecSharedLibrary = 83 => "Cannot exec a shared library directly",
        IllegalByteSequence = 84 => "Illegal byte sequence",
        InterruptedShouldRestart = 85 => "Interrupted system call should be restarted",
        StreamsPipeError = 86 => "Streams pipe error",
        TooManyUsers = 87 => "Too many users",
        OperationOnNonSocket = 88 => "Socket operation on non-socket",
        DestinationAddressRequired = 89 => "Destination address required",
        MessageTooLong = 90 => "Message too long",
        ProtocolWrongTypeForSocket = 91 => "Protocol wrong type for socket",
        ProtocolNotAvailable = 92 => "Protocol not available",
        ProtocolNotSupported = 93 => "Protocol not supported",
        SocketTypeNotSupported = 94 => "Socket type not supported",
        OperationNotSupportedOnEndpoint = 95 => "Operation not supported on transport endpoint",
        ProtocolFamilyNotSupported = 96 => "Protocol family not supported",
        AddressFamilyNotSupported = 97 => "Address family not supported by protocol",
        AddressAlreadyInUse = 98 => "Address already in use",
        CannotAssignRequestedAddress = 99 => "Cannot assign requested address",
        NetworkDown = 100 => "Network is down",
        NetworkUnreachable = 101 => "Network is unreachable",
        NetworkReset = 102 => "Network dropped connection on reset",
        ConnectionAborted = 103 => "Software caused connection abort",
        ConnectionResetByPeer = 104 => "Connection reset by peer",
        NoBufferSpace = 105 => "No buffer space available",
        EndpointAlreadyConnected = 106 => "Transport endpoint is already connected",
        EndpointNotConnected = 107 => "Transport endpoint is not connected",
        CannotSendAfterShutdown = 108 => "Cannot send after transport endpoint shutdown",
        TooManyReferences = 109 => "Too many references: cannot splice",
        ConnectionTimedOut = 110 => "Connection timed out",
        ConnectionRefused = 111 => "Connection refused",
        HostDown = 112 => "Host is down",
        NoRouteToHost = 113 => "No route to host",
        OperationAlreadyInProgress = 114 => "Operation already in progress",
        OperationInProgress = 115 => "Operation now in progress",
        StaleFileHandle = 116 => "Stale file handle",
        StructureNeedsCleaning = 117 => "Structure needs cleaning",
        NotNamedTypeFile = 118 => "Not a XENIX named type file",
        NoSemaphoresAvailable = 119 => "No XENIX semaphores available",
        IsNamedTypeFile = 120 => "Is a named type file",
        RemoteIOError = 121 => "Remote I/O error",
        QuotaExceeded = 122 => "Quota exceeded",
        NoMediumFound = 123 => "No medium found",
        WrongMediumType = 124 => "Wrong medium type",
        OperationCanceled = 125 => "Operation canceled",
        RequiredKeyNotAvailable = 126 => "Required key not available",
        KeyExpired = 127 => "Key has expired",
        KeyRevoked = 128 => "Key has been revoked",
        KeyRejected = 129 => "Key was rejected by service",
        OwnerDied = 130 => "Owner died",
        StateNotRecoverable = 131 => "State not recoverable",
        OperationBlockedByRfKill = 132 => "Operation not possible due to RF-kill",
        HardwarePoison = 133 => "Memory page has hardware error",
    }
);
